# Generated by Django 4.2.2 on 2023-06-17 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
            ],
            options={
                "verbose_name": "alignment",
                "verbose_name_plural": "alignment",
                "db_table": "alignment",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
            ],
            options={
                "verbose_name": "publisher",
                "verbose_name_plural": "publishers",
                "db_table": "publisher",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
            ],
            options={
                "verbose_name": "race",
                "verbose_name_plural": "race",
                "db_table": "race",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SuperPower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "super power & ability",
                "verbose_name_plural": "super powers & abilities",
                "db_table": "super_abilities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("X", "Non-Gendered")],
                        default="X",
                        max_length=1,
                    ),
                ),
                ("eye_color", models.CharField(max_length=255)),
                ("hair_color", models.CharField(max_length=255)),
                ("skin_color", models.CharField(max_length=255)),
                ("weight", models.IntegerField(null=True)),
                ("height", models.IntegerField(default="0", null=True)),
                (
                    "alignment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="API.alignment",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="API.publisher",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="API.race",
                    ),
                ),
            ],
            options={
                "verbose_name": "hero",
                "verbose_name_plural": "heroes",
                "db_table": "hero",
                "ordering": ["name"],
                "unique_together": {
                    (
                        "name",
                        "alignment",
                        "gender",
                        "race",
                        "height",
                        "weight",
                        "skin_color",
                        "hair_color",
                        "eye_color",
                    )
                },
            },
        ),
    ]
