# Generated by Django 4.2.2 on 2023-06-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
            ],
            options={
                "verbose_name": "publisher",
                "verbose_name_plural": "publishers",
                "db_table": "publisher",
                "ordering": ["name"],
            },
        ),
    ]
