# Generated by Django 4.2.2 on 2023-06-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hero",
            name="weight",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
