# Generated by Django 4.2.2 on 2023-06-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0002_alter_hero_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hero",
            name="weight",
            field=models.IntegerField(null=True),
        ),
    ]
