# Generated by Django 4.2.2 on 2023-06-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0002_publisher"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="height",
            field=models.IntegerField(default="0"),
        ),
    ]
