# Generated by Django 4.2.2 on 2023-06-11 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0003_hero_height"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="hero",
            unique_together=set(),
        ),
    ]
