# Generated by Django 4.2.2 on 2023-06-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0005_alter_hero_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hero",
            name="height",
            field=models.IntegerField(default="0", null=True),
        ),
        migrations.AlterField(
            model_name="hero",
            name="weight",
            field=models.IntegerField(null=True),
        ),
    ]
