# Generated by Django 4.2.2 on 2023-06-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0006_alter_hero_height_alter_hero_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuperPower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "super power & ability",
                "verbose_name_plural": "super powers & abilities",
                "db_table": "super_abilities",
                "ordering": ["name"],
            },
        ),
    ]
