# Generated by Django 4.2.2 on 2023-06-13 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0007_superpower"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hero",
            name="alignment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="API.alignment",
            ),
        ),
    ]
