# Generated by Django 4.2.2 on 2023-06-13 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0008_alter_hero_alignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hero",
            name="race",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="API.race"
            ),
        ),
    ]
