# Generated by Django 4.2.2 on 2023-06-13 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0010_alter_hero_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="hero",
            unique_together={
                (
                    "name",
                    "alignment",
                    "gender",
                    "race",
                    "height",
                    "weight",
                    "skin_color",
                    "hair_color",
                    "eye_color",
                )
            },
        ),
    ]
