# Generated by Django 4.2.2 on 2023-06-13 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0011_alter_hero_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuperHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("X", "Non-Gendered")],
                        default="X",
                        max_length=1,
                    ),
                ),
                ("eye_color", models.CharField(max_length=255)),
                ("hair_color", models.CharField(max_length=255)),
                ("skin_color", models.CharField(max_length=255)),
                ("weight", models.IntegerField(null=True)),
                ("height", models.IntegerField(default="0", null=True)),
                (
                    "alignment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="API.alignment",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="API.race",
                    ),
                ),
            ],
            options={
                "verbose_name": "superhero",
                "verbose_name_plural": "superheroes",
                "db_table": "superhero",
                "ordering": ["name"],
                "unique_together": {
                    (
                        "name",
                        "alignment",
                        "gender",
                        "race",
                        "height",
                        "weight",
                        "skin_color",
                        "hair_color",
                        "eye_color",
                    )
                },
            },
        ),
    ]
