# Generated by Django 4.2.2 on 2023-06-13 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0012_superhero"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="publisher",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="API.publisher",
            ),
        ),
    ]
