# Generated by Django 4.2.2 on 2023-06-13 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0013_hero_publisher"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SuperHero",
        ),
    ]
